### ISSUE TITLE
Sidekiq initializer should received basic auth credentials from `Rails.application.secrets`

### ISSUE THREAD

**Issue by diogopms** [freesendmails/free-send-mails-api#15]
https://github.com/freesendmails/free-send-mails-api/blob/master/config/initializers/sidekiq.rb#L5

@grassiricardo, what do you think?

**Comment by diogopms** [comment]
@grassiricardo, what do you think?

**Comment by grassiricardo** [comment]
@diogopms, Ok, great idea: D
