### ISSUE TITLE
Support SSL on www.api.freesendmails.com

### ISSUE THREAD

**Issue by diogopms** [freesendmails/free-send-mails-api#18]
It's not related with the codebase but probably you can add free SSL to support API using `https`.
https://letsencrypt.org/
https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-16-04
cloudflare.com

**Original Url:** http://www.api.freesendmails.com/v1/mails/youmail

**Support https:**
https://www.api.freesendmails.com/v1/mails/youmail or https://api.freesendmails.com/v1/mails/youmail

Thoughts? 🤔

**Comment by grassiricardo** [comment]
@diogopms,I still have not validated the idea of SSL anymore would be a great idea, let's validate this together can it be?

**Comment by diogopms** [comment]
Sure! 👍
