### ISSUE TITLE
Develop functionality to validate emails

### ISSUE THREAD

**Issue by grassiricardo** [freesendmails/free-send-mails-api#4]
Develop a functionality where the user enters with the email that will be the reenter and for validate possible this email will have to be confirmed, a request will be sent via client and the api should be in charge of forwarding the validation email to this email (sender) Informed via client. It should be saved or the email with the release token so that only emails can be triggered after the token is released

**Comment by lira92** [comment]
@grassiricardo I sugest that when the user confirm the email, he is redirect to a screen on free-send-mails-client where he can put a password, this will make it possible for the user can to be authenticated to see all  sent emails with your account, like described here freesendmails/free-send-mails-client#1

**Comment by grassiricardo** [comment]
@lira92 Good suggestion, we have to think about how to do this area for the visualization of emails. More maybe for a first moment to validate the email already enough is not it?

**Comment by lira92** [comment]
Yes, absolutly.

**Comment by grassiricardo** [comment]
finish implementation
