### ISSUE TITLE
Create test for send mail controller.

### ISSUE THREAD

**Issue by grassiricardo** [freesendmails/free-send-mails-api#7]

**Comment by diogopms** [comment]
Can you give more details what is missing in this issue.

Already exist a file called `mails_controller_spec.rb`(probably missing some rspec context, for testing invalid credentials).

**Comment by grassiricardo** [comment]
@diogopms, Have you had any doubts yet?

**Comment by diogopms** [comment]
PR #21 👍 
Waiting for your review :)
